### ISSUE TITLE
[Bug] [Regression] Text Prompt Incorrectly Uses Placeholder Value as the Default Value

### ISSUE THREAD

**Issue by aliasghar98** [bombshell-dev/clack#322]
**Environment**

- OS: Windows
- Node Version: 18.20.4
- Package: @clack/prompts
- Package Version: 0.10.1

**Describe the bug**
Upon not entering anything for a text prompt and having a placeholder value defined, the placeholder value replaces the actual text input for that prompt twice duplicated.

**To Reproduce**
Please refer to the screenshots.

![Image](https://github.com/user-attachments/assets/fc86429c-b95d-4470-89cc-0c7edfe13b81)

![Image](https://github.com/user-attachments/assets/1b56cdff-307f-4f63-bffd-9f8c61d622e3)

![Image](https://github.com/user-attachments/assets/b1ea31ea-a890-4b46-b4dc-e272ba21d07f)

**Comment by manuel3108** [comment]
I think this is describes the same problem as in #321, although this issue focuses on 0.x packages whereas #321 is for 1.0 alpha

**Comment by aliasghar98** [comment]
@43081j I pressed Enter/Return. That gave me the value twice.

**Comment by 43081j** [comment]
i can't seem to reproduce that locally

in 0.x with this:

```ts
const result = await prompts.text({
  message: 'hi',
  placeholder: 'bleep',
  defaultValue: 'bloop'
});
// result is bleep
```

as in, i do get the placeholder and we should fix that. but i can't get it to repeat the value

**Comment by aliasghar98** [comment]
@43081j Yes you're right, I wasn't able to reproduce the repetition of the value. Just the placeholder problem remains. Thanks for looking into this! 

Moving forward, are you guys planning on using the placeholder as the value of `result` in your example if nothing was entered? If yes, I'd have to rethink things on my end.

**Comment by aliasghar98** [comment]
@43081j Here's how to reproduce the bug: https://stackblitz.com/edit/node-yermlvhc?file=package.json,index.js . Looks like there are two issues here:
1. The placeholder value problem.
2. The validate function duplicating the placeholder value.

**Comment by 43081j** [comment]
I have to get agreement from the other maintainers but I'd like to make placeholder a visual thing rather than ever being used as a value

Meanwhile I think we will roll back the change in 0.x that caused this either way

**Comment by 43081j** [comment]
@aliasghar98 can you try out the pkg.pr install in #324 and let me know if it fixes both issues

**Comment by aliasghar98** [comment]
@43081j Just tried it out, works perfectly fine. Thanks!
